// This file was autogenerated by /home/faassen/projects/jspakmantri/node_modules/mantri/lib/../node_modules/closure-tools/closure-bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('src/core.js', ['core'], []);
